on:
  workflow_call:
    inputs:
      REPOSITORY:
        description: 'Image repository'
        type: string
        default: "${{ github.event.repository.name }}"

jobs:
  delete_tag:
    name: "Cleanup untagged ECR images"
    runs-on: ubuntu-20.04
    steps:
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-region: us-east-1
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2
        with:
          registry-type: public

      - name: Cleanup images
        run: |
          IMAGES=$(aws ecr-public describe-images \
            --repository-name $REPOSITORY | jq -r .imageDetails)
          UNTAGGED_IMAGES=$(jq -r 'map(select(has("imageTags") | not))' <<< $IMAGES)
          IMAGE_DIGESTS=$(jq -r '[.[] | "imageDigest=\(.imageDigest)"] | join(" ")' <<< $UNTAGGED_IMAGES)

          aws ecr-public batch-delete-image --repository-name $REPOSITORY --image-ids $IMAGE_DIGESTS
        env:
          REPOSITORY: ${{ inputs.REPOSITORY }}

