on:
  workflow_call:
    inputs:
      REPOSITORY:
        description: 'Image repository'
        type: string
        default: "${{ github.event.repository.name }}"
      TAG:
        description: 'Docker image tag'
        type: string
        required: true

jobs:
  delete_tag:
    name: "Delete ECR tag"
    runs-on: ubuntu-20.04
    # container: amazon/aws-cli:2.17.9
    steps:
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-region: us-east-1
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2
        with:
          registry-type: public

      - name: Delete tag
        run: |
          aws ecr-public batch-delete-image --repository-name $REPOSITORY --image-ids imageTag=$TAG
        env:
          REPOSITORY: ${{ inputs.REPOSITORY }}
          TAG: ${{ inputs.TAG }}
